services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: kcb_admin
      POSTGRES_PASSWORD: kcb_password
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_kcb_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kcb_admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow:
    image: apache/airflow:2.7.1
    restart: always
    command: standalone
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://kcb_admin:kcb_password@postgres/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _PIP_ADDITIONAL_DEPENDENCIES=dbt-postgres pandas plotly sqlalchemy psycopg2-binary pdfplumber
    volumes:
      - ./Financial_Performance_Tracker/dags:/opt/airflow/dags/financials
      - ./MPesa_Loan_Book_Analytics/dags:/opt/airflow/dags/mpesa
      - ./Financial_Performance_Tracker:/opt/airflow/projects/financials
      - ./MPesa_Loan_Book_Analytics:/opt/airflow/projects/mpesa
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8083:8080"

  dashboard:
    image: apache/airflow:2.7.1
    restart: always
    command: bash -c "pip install streamlit plotly sqlalchemy psycopg2-binary pandas && streamlit run /opt/airflow/projects/dashboard_app.py --server.port 8503 --server.address 0.0.0.0"
    ports:
      - "8503:8503"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - .:/opt/airflow/projects
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_kcb_data:
