version: 2

models:
  - name: mart_subsidiary_perf
    columns:
      - name: subsidiary
        tests:
          - not_null
      - name: net_profit_m_kes
        tests:
          - not_null
      - name: cost_to_income_ratio
        tests:
          - not_null

  - name: mart_roe_roa
    columns:
      - name: roe_percent
        tests:
          - not_null
      - name: roa_percent
        tests:
          - not_null

  - name: mart_nim_trend
    columns:
      - name: nim_percent
        tests:
          - not_null
