name: 'float_forecasting'
version: '1.0.0'
config-version: 2

profile: 'float_forecasting'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  float_forecasting:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table

on-run-start:
  - "{{ log('Starting dbt run...', info=true) }}"

on-run-end:
  - "{{ log('dbt run completed!', info=true) }}"

require-dbt-version: [">=1.0.0", "<2.0.0"]
