name: 'mpesa_loans'
version: '1.0.0'
config-version: 2

profile: 'mpesa_loans'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  mpesa_loans:
    staging:
      +materialized: view
    marts:
      +materialized: table
